CREATE TABLE IF NOT EXISTS ACCOUNT(ID VARCHAR(255) PRIMARY KEY);
CREATE TABLE IF NOT EXISTS REGISTER(
  ID BIGINT PRIMARY KEY,
  ACCOUNT_ID VARCHAR(255),
  NAME VARCHAR(255),
  BALANCE DECIMAL(20,2),
  FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID),
  UNIQUE (ACCOUNT_ID, NAME));

INSERT INTO ACCOUNT (ID) VALUES
  SELECT '1' WHERE NOT EXISTS (SELECT ID FROM ACCOUNT WHERE ID = '1') ;
INSERT INTO REGISTER (ID, ACCOUNT_ID, CATEGORY, BALANCE)
  SELECT temp.id, temp.account_id, temp.category, temp.balance
    FROM (VALUES
      (1, '1', 'Wallet', 1000),
      (2, '1', 'Savings', 5000),
      (3, '1', 'Insurance policy', 0),
      (4, '1', 'Food expenses', 0)) AS temp (id, account_id, category, balance)
    WHERE NOT EXISTS (SELECT ID, ACCOUNT_ID, CATEGORY, BALANCE FROM REGISTER WHERE ID = 1);